[project]
name = "par_gpt"
version = "0.1.0"
description = "Par Gpt"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "asyncio>=3.4.3",
    "beautifulsoup4>=4.12.3",
    "boto3>=1.34.0",
    "botocore>=1.34.0",
    "google-api-python-client>=2.145.0",
    "google-auth-httplib2>=0.2.0",
    "google-auth-oauthlib>=1.2.1",
    "html2markdown>=0.1.7",
    "html2text>=2024.2.26",
    "langchain-anthropic>=0.1.23",
    "langchain-aws>=0.1.18",
    "langchain-chroma>=0.1.3",
    "langchain-community>=0.2.12",
    "langchain-core>=0.2.34",
    "langchain-experimental>=0.0.65",
    "langchain-google-community[drive,gmail]>=1.0.8",
    "langchain-google-genai>=1.0.10",
    "langchain-groq>=0.1.9",
    "langchain-ollama>=0.1.1",
    "langchain-openai>=0.1.22",
    "langchain-qdrant>=0.1.3",
    "langchain-text-splitters>=0.2.4",
    "langchain>=0.2.14",
    "langgraph>=0.2.14",
    "markdown>=3.7",
    "markdownify>=0.13.1",
    "ollama>=0.3.3",
    "opentelemetry-exporter-otlp-proto-grpc==1.25.0",
    "pandas>=2.2.2",
    "playwright>=1.47.0",
    "prompt-toolkit>=3.0.0",
    "pydantic-core>=2.20.1",
    "pydantic>=2.8.2",
    "pytesseract>=0.3.13",
    "python-dotenv>=1.0.1",
    "qdrant-client>=1.11.1",
    "rank-bm25>=0.2.2",
    "requests>=2.32.3",
    "rich>=13.7.1",
    "orjson>=3.10.7",
    "tabulate>=0.9.0",
    "tiktoken>=0.7.0",
    "typer>=0.12.5",
    "vecs>=0.4.4",
    "watchdog>=4.0.2",
    "selenium>=4.25.0",
    "webdriver-manager>=4.0.2",
    "git-python>=1.0.3",
    "pathspec>=0.12.1",
    "docutils>=0.21.2",
    "numpy>=1.26.4",
    "matplotlib>=3.9.2",
    "faker>=30.8.2",
    "rich-pixels>=3.0.1",
    "keyring>=25.5.0",
    "praw>=7.8.1",
    "youtube-transcript-api>=0.6.3",
    "tavily-python>=0.5.0",
    "google-search-results>=2.4.2",
    "trafilatura>=2.0.0",
    "langchain-xai>=0.1.0",
    "pygithub>=2.5.0",
    "clipman>=3.3.1",
    "par-ai-core",
]
packages = ["src/par_gpt"]

[project.scripts]
par_gpt = "par_gpt.__main__:app"

[tool.setuptools.package-data]
par_gpt = [
    "py.typed",
    "*/*.png",
    "*/*.md",
    "*/*.tcss",
    "*.png",
    "*.md",
    "*.tcss"
]

[build-system]
requires = ["hatchling", "wheel"]
build-backend = "hatchling.build"

[tool.uv]
dev-dependencies = [
    "build>=1.2.1",
    "twine>=5.1.1",
    "pyright>=1.1.379",
    "pre-commit>=3.8.0",
    "ruff>=0.7.0",
    "types-orjson>=3.6.2",
    "docutils-stubs>=0.0.22",
    "pyinstrument>=5.0.0",
]

[tool.uv.sources]
par-ai-core = { path = "../par_ai_core" }

[tool.hatch.version]
path = "src/par_gpt/__init__.py"

[tool.hatch.build.targets.wheel]
packages = ["src/par_gpt"]
include = [
    "*.py",
    "py.typed",
    "*.png",
    "*.md",
    "*.tcss",
    "*.png",
    "*.md",
    "*.tcss"
]

[tool.hatch.build.targets.sdist]
include = [
    "src/par_gpt",
    "LICENSE",
    "README.md",
    "extraction_prompt.md",
    "pyproject.toml"
]
exclude = [
    "*.pyc",
    "__pycache__",
    "*.so",
    "*.dylib"
]
